### ISSUE TITLE
Metal Slug X Graphic Issue

### ISSUE THREAD

**Issue by dragonstory** [MiSTer-devel/NeoGeo_MiSTer#132]
Hello
I have seen a problem in gameplay.
It is not exist on Real Hardware or emulation.

You can see it on Mister, there is a graphic problem on Maarco's Legs. They are missing. 

This is from Mister Core
https://imgur.com/gHWwNsN

This picture from Original Hardware 
https://imgur.com/FnEduoZ

**Comment by paulb-nl** [comment]
Probably fixed in release 20221224.

**Comment by dragonstory** [comment]
nope it doesnt fixed
i have tested it today and the problem is still there.

**Comment by paulb-nl** [comment]
Which hardware is the "Original Hardware" picture from? Did you make it from your own Neo geo?

What is the easiest way to get those flames there?

**Comment by dragonstory** [comment]
the second picture from my original neogeo mvs hardware
the first picture is from Mister Setup.

on the 3rd stage you are getting fat. Then you will throw the bombs. You will see the graphic glitches when you do that.
I have checked it on emulation too and there is no glitch like that.

**Comment by paulb-nl** [comment]
Ok I have played until the 3rd stage and thrown the bombs but it looks good.

Core version 20221224, System type: MVS, BIOS: Original.
![20221230_123550-screen_c](https://user-images.githubusercontent.com/2227984/210066662-bf3d0633-1b20-4cc0-9671-7da7a457f0a6.png)

**Comment by dragonstory** [comment]
I tested it again with lastest neogeo core and i can see the same problem still.
İt is interesting. What am I doing wrong. Hımmm

![IMG_20221230_151656](https://user-images.githubusercontent.com/12571211/210069594-15d23122-daa8-4a9d-abdd-32103ef25c63.jpg)
![IMG_20221230_151650](https://user-images.githubusercontent.com/12571211/210069610-75e34e9f-1a10-4c79-afa2-40fcb5de565a.jpg)

**Comment by paulb-nl** [comment]
Are you sure you are using the latest version? Check the core version in System -> About. It should say Neogeo 221224.

Are you using the original bios or Universe bios?

**Comment by dragonstory** [comment]
Im using this one

NeoGeo_20221224.rbf
and running with MVS bios.

Tested with unibios and same problem .

**Comment by dragonstory** [comment]
ok i have replace my bios files and tested it again.
and recorded a video

when you throw 1 bomb, there is no problem. But if you throw 2 bomb consecutive you will see the error.

please check the video

https://www.youtube.com/watch?v=wj5xYrGkWT8

**Comment by paulb-nl** [comment]
Can you make the same video with your original Neo geo MVS?

**Comment by dragonstory** [comment]
Hello again
im outside now but i have tersted on this emulation

the first video is taking from mame old versions. 0.220 or something. 
You can see the same issue on there

https://www.youtube.com/watch?v=V23HMjsi9EA


This is the finalburn Neo lastest build i have tested
there is no this problem on this one

https://www.youtube.com/watch?v=Qm7mjN70Lcc


I will test it on the original hardware tomorrow and upload the video .

**Comment by paulb-nl** [comment]
Finalburn Neo is not accurate to hardware because there is no missing sprite in Kabuki clash.

I think the missing legs issue will also appear on your original Neogeo so I await your video.

**Comment by paulb-nl** [comment]
There is a video here from MVS hardware where he throws a bomb when there are enemies below and the same issue happens. 
https://youtu.be/DHfS0h4IKxA?t=1583
![metalslugx_mvs1](https://user-images.githubusercontent.com/2227984/210259971-1566dedd-1db2-4920-9f38-0139c0731411.jpg)
